# Generated by Django 5.2.15 on 2026-08-01 16:06

import accounts.managers
import accounts.utils.ids
import accounts.utils.upload_paths
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django_countries.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('public_id', models.CharField(db_index=True, default=accounts.utils.ids.generate_public_id, editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(blank=True, db_index=True, help_text='Public handle. Auto-generated from your email if left blank.', max_length=50, unique=True, verbose_name='Username')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Phone number')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last name')),
                ('born_date', models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True, verbose_name='Birth date')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='Gender')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('is_staff', models.BooleanField(default=False, help_text='Can access Django administration.', verbose_name='Staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('accepts_sms', models.BooleanField(default=True, verbose_name='Accept SMS notifications')),
                ('accepts_marketing_emails', models.BooleanField(default=True, verbose_name='Accept marketing emails')),
                ('preferred_language', models.CharField(default='en', max_length=10, verbose_name='Preferred language')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Email verified at')),
                ('phone_number_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Phone verified at')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last login IP')),
                ('last_login_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Last login country')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Last activity')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, default=accounts.utils.ids.generate_public_id, editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='e.g. Home, Office.', max_length=100, verbose_name='Label')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='Receiver name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone number')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('province', models.CharField(max_length=64, verbose_name='Province/State')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal code')),
                ('address', models.TextField(verbose_name='Street address')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, default=accounts.utils.ids.generate_public_id, editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=accounts.utils.upload_paths.profile_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Avatar')),
                ('display_name', models.CharField(blank=True, max_length=150, verbose_name='Display name')),
                ('biography', models.TextField(blank=True, verbose_name='Biography')),
                ('points', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Points')),
                ('level', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Level')),
                ('is_private', models.BooleanField(default=False, help_text='When enabled, only a minimal profile page is shown to other visitors.', verbose_name='Private profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, default=accounts.utils.ids.generate_public_id, editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(blank=True, max_length=2048)),
                ('activation_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('priority', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, upload_to=accounts.utils.upload_paths.rank_image_upload_path)),
            ],
            options={
                'ordering': ['-priority'],
                'constraints': [models.UniqueConstraint(fields=('priority',), name='unique_rank_priority')],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='unique_username_ci'),
        ),
    ]
