# Generated by Django 6.0.8 on 2026-09-22 16:53

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
import djmoney.money
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Pricing FAQ',
                'verbose_name_plural': 'Pricing FAQs',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Short description')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('starting_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('IRT', 'IRT T'), ('USD', 'USD $')], default='USD', editable=False, max_length=3)),
                ('starting_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=12, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0, 'USD'))], verbose_name='Starting price')),
                ('billing_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], db_index=True, default='fixed', max_length=20, verbose_name='Billing type')),
                ('badge', models.CharField(blank=True, help_text='Popular, Best Value, New, ...', max_length=40, verbose_name='Badge')),
                ('icon', models.CharField(blank=True, help_text='Material Symbols icon name', max_length=50, verbose_name='Icon')),
                ('featured', models.BooleanField(db_index=True, default=False, verbose_name='Featured')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Order')),
                ('estimated_delivery_days', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Estimated delivery (days)')),
                ('revisions', models.PositiveSmallIntegerField(default=3, verbose_name='Revisions')),
                ('support_days', models.PositiveSmallIntegerField(default=30, verbose_name='Support (days)')),
                ('button_text', models.CharField(default='Get Started', max_length=50, verbose_name='Button text')),
                ('button_url', models.URLField(blank=True, verbose_name='Button URL')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ('order', 'id'),
                'indexes': [models.Index(fields=['active', 'featured', 'order'], name='pricing_pla_active_8c587a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Description')),
                ('included', models.BooleanField(default=True, verbose_name='Included')),
                ('highlight', models.BooleanField(default=False, help_text='Highlight this feature in UI.', verbose_name='Highlight')),
                ('icon', models.CharField(default='check_circle', max_length=50, verbose_name='Icon')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pricing.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Plan Feature',
                'verbose_name_plural': 'Plan Features',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean')], default='text', max_length=20, verbose_name='Value type')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='pricing.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Plan Attribute',
                'verbose_name_plural': 'Plan Attributes',
                'ordering': ('order', 'id'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('plan', 'name'), name='unique_plan_attribute_name')],
            },
        ),
    ]
