"""
Django settings for configuration project.

Generated by 'django-admin startproject' using Django 5.2.15.
"""

from datetime import timedelta
from os import getenv
from pathlib import Path
from dj_database_url import config as database_config
from django.core.exceptions import ImproperlyConfigured
from django.templatetags.static import static
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()

SECRET_KEY = getenv("SECRET_KEY", "")
DEBUG = getenv("DEBUG", "FALSE") == "TRUE"

if not DEBUG and not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY must be set in the environment when DEBUG is off.")

RENDER_EXTERNAL_HOSTNAME = getenv("RENDER_EXTERNAL_HOSTNAME")

ALLOWED_HOSTS = [
    host
    for host in getenv(
        "ALLOWED_HOSTS",
        RENDER_EXTERNAL_HOSTNAME or "127.0.0.1",
    ).split(",")
    if host
]
# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.humanize",
]

THIRD_PARTY_APPS = [
    # Debug
    "debug_toolbar",
    "django_extensions",

    # REST
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",

    # CORS — required because CorsMiddleware is enabled below.
    "corsheaders",

    # Auth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "axes",

    # Forms
    "crispy_forms",
    "widget_tweaks",

    # Filters
    "django_filters",

    # Storage
    "storages",

    # Phone
    "phonenumber_field",

    # Cache
    "django_redis",

    # Translation
    "parler",
    "rosetta",

    # History
    "simple_history",

    # Money
    "djmoney",

    # Countries
    "django_countries",
]

LOCAL_APPS = [
    "accounts.apps.AccountsConfig",
    "core.apps.CoreConfig",
    "catalog.apps.CatalogConfig",
    "weblog.apps.WeblogConfig",
    "questions.apps.QuestionsConfig",
]

HIGH_PRIORITY_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.import_export",
]

INSTALLED_APPS = HIGH_PRIORITY_APPS + DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "axes.middleware.AxesMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "configuration.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.website_information",
            ],
        },
    },
]

WSGI_APPLICATION = "configuration.wsgi.application"
SITE_ID = 1


# Database

DATABASES = {
    "default": database_config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

AUTH_USER_MODEL = "accounts.User"


# Internationalization

LANGUAGE_CODE = "en"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

LANGUAGES = (
    ("en", "English"),
    ("fa", "Persian"),
)


# Static & media files

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Django 4.2+ way of declaring storages (STATICFILES_STORAGE alone is
# deprecated); this keeps the same Whitenoise-compressed-manifest backend
# for static files while using the default backend for uploaded media.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Email
# Uses Django's built-in SMTP backend — swap for `anymail` only if you need
# a specific ESP's extra features (templates, tracking, etc.), and remember
# to add "anymail" to THIRD_PARTY_APPS if you do.

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = getenv("EMAIL_HOST", "localhost")
EMAIL_PORT = int(getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = getenv("EMAIL_USE_TLS", "TRUE") == "TRUE"
DEFAULT_FROM_EMAIL = getenv("DEFAULT_FROM_EMAIL", "webmaster@localhost")


# django-allauth
# NOTE: include allauth's own urls in the project's root urlconf for the
# templates in `accounts` that link to account_signup / account_email /
# account_reset_password / account_change_password:
#     path("accounts/", include("allauth.urls"))

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none"

LOGIN_REDIRECT_URL = "/"
LOGIN_URL = "accounts:sign-in"
LOGOUT_REDIRECT_URL = "/"
LOGOUT_URL = "accounts:sign-out"


# django-axes (login throttling)

AXES_FAILURE_LIMIT = 10
AXES_COOLOFF_TIME = timedelta(seconds=1)
AXES_LOCKOUT_PARAMETERS = ["ip_address"]


# Django REST Framework

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Project API",
    "VERSION": "1.0.0",
}


# django-cors-headers
# Empty allow-list by default — set explicitly per environment instead of
# defaulting to "allow everything".

CORS_ALLOWED_ORIGINS = [
    origin for origin in getenv("CORS_ALLOWED_ORIGINS", "").split(",") if origin
]


# Cache

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": getenv("REDIS_CACHE_URL", "redis://127.0.0.1:6379/0"),
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    }
}


# django-unfold (admin theme)

UNFOLD = {
    "SITE_TITLE": "Shopping Website",
    "SITE_HEADER": "Shopping Website",
    "SITE_SUBHEADER": "Administration",
    "SITE_SYMBOL": "shopping_cart",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SITE_DROPDOWN": [
        {"icon": "public", "title": "Visit Store", "link": "/"},
    ],
    "SIDEBAR": {
        "show_search": True,
        "command_search": True,
    },
    "COLORS": {
        "primary": {
            "50": "#eff6ff",
            "100": "#dbeafe",
            "200": "#bfdbfe",
            "300": "#93c5fd",
            "400": "#60a5fa",
            "500": "#3b82f6",
            "600": "#2563eb",
            "700": "#1d4ed8",
            "800": "#1e40af",
            "900": "#1e3a8a",
            "950": "#172554",
        }
    },
    "STYLES": [lambda request: static("vendor/material-symbols/rounded.css")],
    "SCRIPTS": [lambda request: static("admin/custom.js")],
}


# django-money

CURRENCIES = ("USD", "EUR", "IRT")
CURRENCY_CHOICES = [("USD", "USD $"), ("EUR", "EUR €"), ("IRT", "IRT T")]
SERIALIZATION_MODULES = {"json": "djmoney.serializers"}


# django-parler

PARLER_LANGUAGES = {
    None: (
        {"code": "en"},
        {"code": "fa"},
    ),
    "default": {
        "fallbacks": ["en"],
        "hide_untranslated": False,
    },
}
PARLER_DEFAULT_LANGUAGE_CODE = "en"


# Uploads

FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024


# Security

X_FRAME_OPTIONS = "DENY"
SECURE_CONTENT_TYPE_NOSNIFF = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# Only force HTTPS-only cookies once you're actually serving over HTTPS —
# forcing this under DEBUG would break local development over plain http.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG


# Logging

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "[{levelname}] {asctime} {name}: {message}", "style": "{"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "simple"},
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}


# LLM

LM_STUDIO_BASE_URL = "http://127.0.0.1:1234/v1"

LM_STUDIO_MODEL = "empero-ai/qwen3.8-2b-distill"

LM_STUDIO_TIMEOUT = 30

LM_STUDIO_MAX_IMAGES = 8

# Celery

CELERY_BROKER_URL = getenv(
    "CELERY_BROKER_URL",
    "redis://127.0.0.1:6379/1",
)

CELERY_RESULT_BACKEND = getenv(
    "CELERY_RESULT_BACKEND",
    "redis://127.0.0.1:6379/2",
)

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = USE_TZ

CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 300
CELERY_TASK_SOFT_TIME_LIMIT = 270

# Questions

QUESTIONS_ENABLED = True

QUESTIONS_SUBMISSION_MAX_CODE_SIZE = 256 * 1024
QUESTIONS_MAX_TESTS_PER_QUESTION = 100

QUESTIONS_DEFAULT_TIMEOUT = 2
QUESTIONS_MAX_TIMEOUT = 10

QUESTIONS_MAX_OUTPUT_SIZE = 64 * 1024

QUESTIONS_MAX_EXECUTION_MEMORY = "128m"
QUESTIONS_MAX_EXECUTION_CPU = 1
QUESTIONS_MAX_PROCESSES = 32

QUESTIONS_MAX_CONCURRENT_EXECUTIONS = 4

QUESTIONS_ALLOW_MANUAL_REVIEW = True
QUESTIONS_SANITIZE_MARKDOWN = False

QUESTIONS_EXECUTION_BACKEND = "docker"

QUESTIONS_PYTHON_IMAGE = "questions-python:3.14-sandbox"













WEBSITE_TITLE = "AxiomLite"