"""
Django settings for configuration project.

Generated by 'django-admin startproject' using Django 5.2.15.
"""

from datetime import timedelta
from os import getenv
from pathlib import Path

from dj_database_url import config as database_config
from django.core.exceptions import ImproperlyConfigured
from django.templatetags.static import static
from dotenv import load_dotenv

# -----------------------------------------------------------------------------
# Base configuration
# -----------------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()


def env(name: str, default: str = "") -> str:
    """Return an environment variable with surrounding whitespace removed."""
    return getenv(name, default).strip()


def env_bool(name: str, default: bool = False) -> bool:
    """Read a boolean environment variable."""
    value = env(name, str(default))

    return value.lower() in {
        "1",
        "true",
        "yes",
        "on",
    }


def env_int(name: str, default: int) -> int:
    """Read an integer environment variable."""
    value = env(name, str(default))

    try:
        return int(value)
    except ValueError as exc:
        raise ImproperlyConfigured(f"{name} must be a valid integer.") from exc


def env_list(name: str, default: str = "") -> list[str]:
    """Read a comma-separated environment variable."""
    return [item.strip() for item in env(name, default).split(",") if item.strip()]


# -----------------------------------------------------------------------------
# Core Django settings
# -----------------------------------------------------------------------------

SECRET_KEY = env("SECRET_KEY")

DEBUG = env_bool("DEBUG", False)

if not DEBUG and not SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY must be set in the environment when DEBUG is off."
    )


SITE_ID = env_int("SITE_ID", 1)

WEBSITE_TITLE = env("WEBSITE_TITLE", "AxiomLite")

RENDER_EXTERNAL_HOSTNAME = env("RENDER_EXTERNAL_HOSTNAME")

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    RENDER_EXTERNAL_HOSTNAME or "127.0.0.1,localhost",
)


# -----------------------------------------------------------------------------
# Application definition
# -----------------------------------------------------------------------------

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.humanize",
]

THIRD_PARTY_APPS = [
    # Debug
    "debug_toolbar",
    "django_extensions",
    # REST
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    # CORS
    "corsheaders",
    # Auth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "axes",
    # Forms
    "crispy_forms",
    "widget_tweaks",
    # Filters
    "django_filters",
    # Storage
    "storages",
    # Phone
    "phonenumber_field",
    # Cache
    "django_redis",
    # Translation
    "parler",
    "rosetta",
    # History
    "simple_history",
    # Money
    "djmoney",
    # Countries
    "django_countries",
]

LOCAL_APPS = [
    "accounts.apps.AccountsConfig",
    "core.apps.CoreConfig",
    "catalog.apps.CatalogConfig",
    "weblog.apps.WeblogConfig",
    "questions.apps.QuestionsConfig",
    "pricing.apps.PricingConfig",
]

HIGH_PRIORITY_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.import_export",
]

INSTALLED_APPS = HIGH_PRIORITY_APPS + DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS


# -----------------------------------------------------------------------------
# Middleware
# -----------------------------------------------------------------------------

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "axes.middleware.AxesMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# -----------------------------------------------------------------------------
# URLs / templates
# -----------------------------------------------------------------------------

ROOT_URLCONF = "configuration.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.website_information",
            ],
        },
    },
]

WSGI_APPLICATION = "configuration.wsgi.application"


# -----------------------------------------------------------------------------
# Database
# -----------------------------------------------------------------------------

DATABASE_URL = env("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": database_config(
            DATABASE_URL,
            conn_max_age=env_int("DATABASE_CONN_MAX_AGE", 600),
            conn_health_checks=env_bool(
                "DATABASE_CONN_HEALTH_CHECKS",
                True,
            ),
        )
    }
else:
    DATABASE_ENGINE = env("DATABASE_ENGINE", "sqlite").lower()

    SUPPORTED_DATABASES = {
        "sqlite": "django.db.backends.sqlite3",
        "mysql": "django.db.backends.mysql",
        "postgresql": "django.db.backends.postgresql",
    }

    if DATABASE_ENGINE not in SUPPORTED_DATABASES:
        raise ImproperlyConfigured(
            "DATABASE_ENGINE must be one of: sqlite, mysql, postgresql."
        )

    if DATABASE_ENGINE == "sqlite":
        DATABASES = {
            "default": {
                "ENGINE": SUPPORTED_DATABASES["sqlite"],
                "NAME": BASE_DIR / env("SQLITE_NAME", "db.sqlite3"),
                "CONN_MAX_AGE": env_int(
                    "DATABASE_CONN_MAX_AGE",
                    600,
                ),
                "CONN_HEALTH_CHECKS": env_bool(
                    "DATABASE_CONN_HEALTH_CHECKS",
                    True,
                ),
            }
        }
    else:
        DATABASES = {
            "default": {
                "ENGINE": SUPPORTED_DATABASES[DATABASE_ENGINE],
                "NAME": env("DATABASE_NAME"),
                "USER": env("DATABASE_USER"),
                "PASSWORD": env("DATABASE_PASSWORD"),
                "HOST": env("DATABASE_HOST", "127.0.0.1"),
                "PORT": env(
                    "DATABASE_PORT",
                    "3306" if DATABASE_ENGINE == "mysql" else "5432",
                ),
                "CONN_MAX_AGE": env_int(
                    "DATABASE_CONN_MAX_AGE",
                    600,
                ),
                "CONN_HEALTH_CHECKS": env_bool(
                    "DATABASE_CONN_HEALTH_CHECKS",
                    True,
                ),
            }
        }

# -----------------------------------------------------------------------------
# Password validation
# -----------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "MinimumLengthValidator"),
        "OPTIONS": {
            "min_length": env_int("PASSWORD_MIN_LENGTH", 8),
        },
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "CommonPasswordValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "NumericPasswordValidator"),
    },
]

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

AUTH_USER_MODEL = "accounts.User"


# -----------------------------------------------------------------------------
# Internationalization
# -----------------------------------------------------------------------------

LANGUAGE_CODE = env("LANGUAGE_CODE", "en")
TIME_ZONE = env("TIME_ZONE", "UTC")

USE_I18N = True
USE_TZ = True

LANGUAGES = (
    ("en", "English"),
    ("fa", "Persian"),
)


# -----------------------------------------------------------------------------
# Static and media files
# -----------------------------------------------------------------------------

STATIC_URL = env("STATIC_URL", "static/")
STATIC_ROOT = BASE_DIR / env("STATIC_ROOT", "staticfiles")

STATICFILES_DIRS = [
    BASE_DIR / env("STATICFILES_DIR", "static"),
]

MEDIA_URL = env("MEDIA_URL", "/media/")
MEDIA_ROOT = BASE_DIR / env("MEDIA_ROOT", "media")

STORAGES = {
    "default": {
        "BACKEND": env(
            "DEFAULT_STORAGE_BACKEND",
            "django.core.files.storage.FileSystemStorage",
        ),
    },
    "staticfiles": {
        "BACKEND": env(
            "STATICFILES_STORAGE_BACKEND",
            "whitenoise.storage.CompressedManifestStaticFilesStorage",
        ),
    },
}


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# -----------------------------------------------------------------------------
# Email
# -----------------------------------------------------------------------------

EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend",
)

EMAIL_HOST = env("EMAIL_HOST", "localhost")
EMAIL_PORT = env_int("EMAIL_PORT", 587)

EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")

EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)

EMAIL_TIMEOUT = env_int("EMAIL_TIMEOUT", 30)

DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL",
    "webmaster@localhost",
)

SERVER_EMAIL = env(
    "SERVER_EMAIL",
    DEFAULT_FROM_EMAIL,
)


# -----------------------------------------------------------------------------
# django-allauth
# -----------------------------------------------------------------------------

ACCOUNT_LOGIN_METHODS = {"email"}

ACCOUNT_SIGNUP_FIELDS = [
    "email*",
    "password1*",
    "password2*",
]

ACCOUNT_EMAIL_VERIFICATION = env(
    "ACCOUNT_EMAIL_VERIFICATION",
    "none",
)

LOGIN_REDIRECT_URL = env("LOGIN_REDIRECT_URL", "/")
LOGIN_URL = env("LOGIN_URL", "accounts:sign-in")
LOGOUT_REDIRECT_URL = env("LOGOUT_REDIRECT_URL", "/")
LOGOUT_URL = env("LOGOUT_URL", "accounts:sign-out")


# -----------------------------------------------------------------------------
# django-axes
# -----------------------------------------------------------------------------

AXES_FAILURE_LIMIT = env_int("AXES_FAILURE_LIMIT", 10)

AXES_COOLOFF_TIME = timedelta(
    seconds=env_int("AXES_COOLOFF_SECONDS", 1),
)

AXES_LOCKOUT_PARAMETERS = env_list(
    "AXES_LOCKOUT_PARAMETERS",
    "ip_address",
)


# -----------------------------------------------------------------------------
# Django REST Framework
# -----------------------------------------------------------------------------

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    "DEFAULT_SCHEMA_CLASS": ("drf_spectacular.openapi.AutoSchema"),
}

SPECTACULAR_SETTINGS = {
    "TITLE": env("API_TITLE", "AxiomLite API"),
    "VERSION": env("API_VERSION", "1.0.0"),
    "DESCRIPTION": env(
        "API_DESCRIPTION",
        "AxiomLite API",
    ),
}


# -----------------------------------------------------------------------------
# django-cors-headers
# -----------------------------------------------------------------------------

CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
)

CORS_ALLOW_CREDENTIALS = env_bool(
    "CORS_ALLOW_CREDENTIALS",
    False,
)

CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
)


# -----------------------------------------------------------------------------
# Cache
# -----------------------------------------------------------------------------

REDIS_CACHE_URL = env(
    "REDIS_CACHE_URL",
    "redis://127.0.0.1:6379/0",
)

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_CACHE_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}


# -----------------------------------------------------------------------------
# django-unfold
# -----------------------------------------------------------------------------

UNFOLD = {
    "SITE_TITLE": env(
        "UNFOLD_SITE_TITLE",
        WEBSITE_TITLE,
    ),
    "SITE_HEADER": env(
        "UNFOLD_SITE_HEADER",
        WEBSITE_TITLE,
    ),
    "SITE_SUBHEADER": env(
        "UNFOLD_SITE_SUBHEADER",
        "Administration",
    ),
    "SITE_SYMBOL": env(
        "UNFOLD_SITE_SYMBOL",
        "shopping_cart",
    ),
    "SHOW_HISTORY": env_bool(
        "UNFOLD_SHOW_HISTORY",
        True,
    ),
    "SHOW_VIEW_ON_SITE": env_bool(
        "UNFOLD_SHOW_VIEW_ON_SITE",
        True,
    ),
    "SITE_DROPDOWN": [
        {
            "icon": "public",
            "title": env(
                "UNFOLD_SITE_DROPDOWN_TITLE",
                "Visit Store",
            ),
            "link": env(
                "UNFOLD_SITE_DROPDOWN_LINK",
                "/",
            ),
        },
    ],
    "SIDEBAR": {
        "show_search": env_bool(
            "UNFOLD_SIDEBAR_SEARCH",
            True,
        ),
        "command_search": env_bool(
            "UNFOLD_COMMAND_SEARCH",
            True,
        ),
    },
    "COLORS": {
        "primary": {
            "50": "#eff6ff",
            "100": "#dbeafe",
            "200": "#bfdbfe",
            "300": "#93c5fd",
            "400": "#60a5fa",
            "500": "#3b82f6",
            "600": "#2563eb",
            "700": "#1d4ed8",
            "800": "#1e40af",
            "900": "#1e3a8a",
            "950": "#172554",
        }
    },
    "STYLES": [lambda request: static("styles/rounded.css")],
    "SCRIPTS": [lambda request: static("admin/custom.js")],
}


# -----------------------------------------------------------------------------
# django-money
# -----------------------------------------------------------------------------

CURRENCIES = ("USD", "EUR", "IRT")

CURRENCY_CHOICES = [
    ("USD", "USD $"),
    ("EUR", "EUR €"),
    ("IRT", "IRT T"),
]

SERIALIZATION_MODULES = {
    "json": "djmoney.serializers",
}


# -----------------------------------------------------------------------------
# django-parler
# -----------------------------------------------------------------------------

PARLER_LANGUAGES = {
    None: (
        {"code": "en"},
        {"code": "fa"},
    ),
    "default": {
        "fallbacks": ["en"],
        "hide_untranslated": False,
    },
}

PARLER_DEFAULT_LANGUAGE_CODE = env(
    "PARLER_DEFAULT_LANGUAGE_CODE",
    "en",
)


# -----------------------------------------------------------------------------
# Uploads
# -----------------------------------------------------------------------------

FILE_UPLOAD_MAX_MEMORY_SIZE = env_int(
    "FILE_UPLOAD_MAX_MEMORY_SIZE",
    10 * 1024 * 1024,
)

DATA_UPLOAD_MAX_MEMORY_SIZE = env_int(
    "DATA_UPLOAD_MAX_MEMORY_SIZE",
    10 * 1024 * 1024,
)


# -----------------------------------------------------------------------------
# Security
# -----------------------------------------------------------------------------

X_FRAME_OPTIONS = env(
    "X_FRAME_OPTIONS",
    "DENY",
)

SECURE_CONTENT_TYPE_NOSNIFF = env_bool(
    "SECURE_CONTENT_TYPE_NOSNIFF",
    True,
)

SESSION_COOKIE_HTTPONLY = env_bool(
    "SESSION_COOKIE_HTTPONLY",
    True,
)

CSRF_COOKIE_HTTPONLY = env_bool(
    "CSRF_COOKIE_HTTPONLY",
    True,
)

SESSION_COOKIE_SECURE = env_bool(
    "SESSION_COOKIE_SECURE",
    not DEBUG,
)

CSRF_COOKIE_SECURE = env_bool(
    "CSRF_COOKIE_SECURE",
    not DEBUG,
)

SECURE_SSL_REDIRECT = env_bool(
    "SECURE_SSL_REDIRECT",
    False,
)

SECURE_HSTS_SECONDS = env_int(
    "SECURE_HSTS_SECONDS",
    0,
)

SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS",
    False,
)

SECURE_HSTS_PRELOAD = env_bool(
    "SECURE_HSTS_PRELOAD",
    False,
)

SECURE_REFERRER_POLICY = env(
    "SECURE_REFERRER_POLICY",
    "same-origin",
)

SECURE_CROSS_ORIGIN_OPENER_POLICY = env(
    "SECURE_CROSS_ORIGIN_OPENER_POLICY",
    "same-origin",
)

USE_X_FORWARDED_HOST = env_bool(
    "USE_X_FORWARDED_HOST",
    False,
)

SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https")
    if env_bool("SECURE_PROXY_SSL_HEADER_ENABLED", False)
    else None
)


# -----------------------------------------------------------------------------
# Session
# -----------------------------------------------------------------------------

SESSION_COOKIE_AGE = env_int(
    "SESSION_COOKIE_AGE",
    1209600,
)

SESSION_SAVE_EVERY_REQUEST = env_bool(
    "SESSION_SAVE_EVERY_REQUEST",
    False,
)

SESSION_EXPIRE_AT_BROWSER_CLOSE = env_bool(
    "SESSION_EXPIRE_AT_BROWSER_CLOSE",
    False,
)


# -----------------------------------------------------------------------------
# Logging
# -----------------------------------------------------------------------------

LOG_LEVEL = env(
    "LOG_LEVEL",
    "INFO",
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": ("[{levelname}] {asctime} " "{name}: {message}"),
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
}


# -----------------------------------------------------------------------------
# LLM / LM Studio
# -----------------------------------------------------------------------------

LM_STUDIO_BASE_URL = env(
    "LM_STUDIO_BASE_URL",
    "http://127.0.0.1:1234/v1",
)

LM_STUDIO_MODEL = env(
    "LM_STUDIO_MODEL",
    "empero-ai/qwen3.8-2b-distill",
)

LM_STUDIO_TIMEOUT = env_int(
    "LM_STUDIO_TIMEOUT",
    30,
)

LM_STUDIO_MAX_IMAGES = env_int(
    "LM_STUDIO_MAX_IMAGES",
    8,
)


# -----------------------------------------------------------------------------
# Celery
# -----------------------------------------------------------------------------

CELERY_BROKER_URL = env(
    "CELERY_BROKER_URL",
    "redis://127.0.0.1:6379/1",
)

CELERY_RESULT_BACKEND = env(
    "CELERY_RESULT_BACKEND",
    "redis://127.0.0.1:6379/2",
)

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = USE_TZ

CELERY_TASK_TRACK_STARTED = env_bool(
    "CELERY_TASK_TRACK_STARTED",
    True,
)

CELERY_TASK_TIME_LIMIT = env_int(
    "CELERY_TASK_TIME_LIMIT",
    300,
)

CELERY_TASK_SOFT_TIME_LIMIT = env_int(
    "CELERY_TASK_SOFT_TIME_LIMIT",
    270,
)


# -----------------------------------------------------------------------------
# Questions
# -----------------------------------------------------------------------------

QUESTIONS_ENABLED = env_bool(
    "QUESTIONS_ENABLED",
    True,
)

QUESTIONS_SUBMISSION_MAX_CODE_SIZE = env_int(
    "QUESTIONS_SUBMISSION_MAX_CODE_SIZE",
    256 * 1024,
)

QUESTIONS_MAX_TESTS_PER_QUESTION = env_int(
    "QUESTIONS_MAX_TESTS_PER_QUESTION",
    100,
)

QUESTIONS_DEFAULT_TIMEOUT = env_int(
    "QUESTIONS_DEFAULT_TIMEOUT",
    2,
)

QUESTIONS_MAX_TIMEOUT = env_int(
    "QUESTIONS_MAX_TIMEOUT",
    10,
)

QUESTIONS_MAX_OUTPUT_SIZE = env_int(
    "QUESTIONS_MAX_OUTPUT_SIZE",
    64 * 1024,
)

QUESTIONS_MAX_EXECUTION_MEMORY = env(
    "QUESTIONS_MAX_EXECUTION_MEMORY",
    "128m",
)

QUESTIONS_MAX_EXECUTION_CPU = env_int(
    "QUESTIONS_MAX_EXECUTION_CPU",
    1,
)

QUESTIONS_MAX_PROCESSES = env_int(
    "QUESTIONS_MAX_PROCESSES",
    32,
)

QUESTIONS_MAX_CONCURRENT_EXECUTIONS = env_int(
    "QUESTIONS_MAX_CONCURRENT_EXECUTIONS",
    4,
)

QUESTIONS_ALLOW_MANUAL_REVIEW = env_bool(
    "QUESTIONS_ALLOW_MANUAL_REVIEW",
    True,
)

QUESTIONS_SANITIZE_MARKDOWN = env_bool(
    "QUESTIONS_SANITIZE_MARKDOWN",
    False,
)

QUESTIONS_EXECUTION_BACKEND = env(
    "QUESTIONS_EXECUTION_BACKEND",
    "docker",
)

QUESTIONS_PYTHON_IMAGE = env(
    "QUESTIONS_PYTHON_IMAGE",
    "questions-python:3.14-sandbox",
)
