# Generated by Django 6.1 on 2026-08-24 08:17

import accounts.utils.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, default=accounts.utils.ids.generate_public_id, editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, default=accounts.utils.ids.generate_public_id, editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('supports_automatic_testing', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='questions_l_is_acti_1081e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, default=accounts.utils.ids.generate_public_id, editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12)),
                ('evaluation_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('hybrid', 'Hybrid')], default='automatic', max_length=10)),
                ('evaluator', models.CharField(default='manual', max_length=80)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.IntegerField(db_index=True, default=0)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questions.language')),
                ('tags', models.ManyToManyField(blank=True, related_name='questions', to='questions.tag')),
            ],
            options={
                'ordering': ['sort_order', '-created_at', 'id'],
                'permissions': [('publish_question', 'Can publish question'), ('manage_test_cases', 'Can manage test cases'), ('review_submission', 'Can review submission')],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, default=accounts.utils.ids.generate_public_id, editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('manual_review', 'Manual review')], db_index=True, default='pending', max_length=20)),
                ('automatic_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('manual_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('final_score', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=6, null=True)),
                ('passed_tests_count', models.PositiveIntegerField(default=0)),
                ('failed_tests_count', models.PositiveIntegerField(default=0)),
                ('total_tests_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('manual_feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='questions.language')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='questions.question')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_question_submissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, default=accounts.utils.ids.generate_public_id, editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('inputs', models.JSONField(default=list)),
                ('expected_outputs', models.JSONField(default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('timeout', models.DecimalField(decimal_places=3, default=2, max_digits=6)),
                ('comparison_mode', models.CharField(choices=[('exact', 'Exact'), ('trimmed', 'Trimmed'), ('case_insensitive', 'Case insensitive'), ('whitespace_insensitive', 'Whitespace insensitive'), ('numeric', 'Numeric'), ('custom', 'Custom')], default='exact', max_length=32)),
                ('is_hidden', models.BooleanField(db_index=True, default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='questions.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, default=accounts.utils.ids.generate_public_id, editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error'), ('timeout', 'Timeout'), ('security_error', 'Security error'), ('output_limit_exceeded', 'Output limit exceeded')], max_length=32)),
                ('passed', models.BooleanField(default=False)),
                ('input_snapshot', models.JSONField(default=list)),
                ('expected_output_snapshot', models.JSONField(default=list)),
                ('actual_output', models.TextField(blank=True)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='questions.submission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='questions.testcase')),
            ],
            options={
                'ordering': ['test_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'question', '-created_at'], name='questions_s_user_id_1b29fb_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['question', 'status'], name='questions_s_questio_840261_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['question', 'final_score'], name='questions_s_questio_d3c5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'final_score'], name='questions_s_user_id_3eb934_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['status', 'difficulty'], name='questions_q_status_cc3096_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['status', 'language'], name='questions_q_status_5a5b02_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['status', 'created_at'], name='questions_q_status_61398b_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_featured', 'status'], name='questions_q_is_feat_e361d8_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['question', 'is_active', 'order'], name='questions_t_questio_b9a0cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='questions_testcase_question_order'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['submission', 'test_order'], name='questions_t_submiss_d552ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='testresult',
            constraint=models.UniqueConstraint(fields=('submission', 'test_order'), name='questions_result_submission_order'),
        ),
    ]
