# Generated by Django 6.1 on 2026-08-24 08:16

import catalog.utils.file
import catalog.utils.id
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import djmoney.models.fields
import djmoney.money
import model_utils.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OffCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('code', models.CharField(help_text='Unique alphanumeric code for the discount.', max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.CharField(blank=True, help_text='Optional human-readable description of the offer.', max_length=255)),
                ('starts_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='When the code becomes active.')),
                ('ends_at', models.DateTimeField(blank=True, help_text='Expiry datetime. Blank = never expires.', null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage off (0–100). Mutually exclusive with fixed_discount_amount.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('fixed_discount_amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('IRT', 'IRT T'), ('USD', 'USD $')], default=None, editable=False, max_length=3, null=True)),
                ('fixed_discount_amount', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, help_text='Fixed monetary discount. Mutually exclusive with discount_percent.', max_digits=12, null=True)),
                ('max_discount_per_use_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('IRT', 'IRT T'), ('USD', 'USD $')], default=None, editable=False, max_length=3, null=True)),
                ('max_discount_per_use', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, help_text='Maximum discount that can be applied per single order.', max_digits=14, null=True)),
                ('total_discount_capacity_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('IRT', 'IRT T'), ('USD', 'USD $')], default=None, editable=False, max_length=3, null=True)),
                ('total_discount_capacity', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, help_text='Cumulative discount budget across all uses. Blank = unlimited.', max_digits=14, null=True)),
                ('minimum_order_amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('IRT', 'IRT T'), ('USD', 'USD $')], default=None, editable=False, max_length=3, null=True)),
                ('minimum_order_amount', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, help_text='Order must be at least this value for the code to apply.', max_digits=14, null=True)),
                ('usage_limit', models.IntegerField(blank=True, help_text='Total times this code can be used by anyone.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('usage_limit_per_user', models.SmallIntegerField(blank=True, help_text='Maximum times a single user may use this code.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('usages', models.PositiveIntegerField(default=0, help_text='Running count of redemptions.')),
                ('is_active', models.BooleanField(default=True, help_text='Master on/off switch.')),
            ],
            options={
                'verbose_name': 'Discount Code',
                'verbose_name_plural': 'Discount Codes',
                'ordering': ['-created'],
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_percent__isnull', True), ('fixed_discount_amount__isnull', True), _connector='OR'), name='offcode_one_discount_type')],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('order_id', models.CharField(default=catalog.utils.id.generate_key, editable=False, help_text='Human-readable unique order reference.', max_length=39, unique=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending Payment'), (1, 'Paid'), (2, 'Processing'), (3, 'Shipped'), (4, 'Delivered'), (5, 'Cancelled'), (6, 'Refunded')], default=0)),
                ('currency', models.CharField(default='IRR', help_text='ISO 4217 currency code for this order.', max_length=3)),
                ('subtotal_amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('IRT', 'IRT T'), ('USD', 'USD $')], default='IRR', editable=False, max_length=3)),
                ('subtotal_amount', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(Decimal('0'), 'IRR'), default_currency='IRR', help_text='Sum of item subtotals before any discounts.', max_digits=14)),
                ('coupon_discount_amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('IRT', 'IRT T'), ('USD', 'USD $')], default='IRR', editable=False, max_length=3)),
                ('coupon_discount_amount', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(Decimal('0'), 'IRR'), default_currency='IRR', help_text='Discount applied by a coupon code.', max_digits=12)),
                ('final_amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('IRT', 'IRT T'), ('USD', 'USD $')], default='IRR', editable=False, max_length=3)),
                ('final_amount', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(Decimal('0'), 'IRR'), default_currency='IRR', help_text='Amount payable after discounts.', max_digits=14)),
                ('shipping_address', models.TextField(blank=True)),
                ('billing_address', models.TextField(blank=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('off_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.offcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('description', models.TextField(default='Purchase from our website', max_length=1024)),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Failed'), (3, 'Refunded'), (4, 'Cancelled')], db_index=True, default=0)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('IRT', 'IRT T'), ('USD', 'USD $')], default='IRR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='IRR', help_text='Total amount charged.', max_digits=14)),
                ('value_added_tax', models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='VAT percentage (e.g. 10 for 10%).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('payment_method', models.CharField(blank=True, choices=[('ZARINPAL', 'ZarinPal'), ('INTERNAL', 'Internal Gateway'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH_ON_DELIVERY', 'Cash on Delivery')], max_length=50, null=True)),
                ('payment_id', models.CharField(default=catalog.utils.id.generate_key, editable=False, max_length=39, unique=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Gateway-assigned transaction ID.', max_length=100, unique=True)),
                ('authority', models.CharField(blank=True, db_index=True, help_text='Zarinpal authority token.', max_length=100, unique=True)),
                ('user_ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, unpack_ipv4=True)),
                ('gateway_response', models.TextField(blank=True, help_text='Raw JSON response from the payment gateway.')),
                ('payment_request_time', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='catalog.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(max_length=2048)),
                ('image', models.ImageField(blank=True, default='default-product-image.png', null=True, upload_to=catalog.utils.file.get_product_image_path)),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('IRT', 'IRT T'), ('USD', 'USD $')], default='IRR', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='IRR', help_text='Base price of the product.', max_digits=16, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0, 'IRR'))])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Discount percentage (0–100).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('status', models.SmallIntegerField(choices=[(0, 'Disabled'), (1, 'Enabled'), (2, 'Sold Out'), (3, 'Discontinued')], default=1)),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('selling_count', models.PositiveBigIntegerField(default=0, editable=False)),
                ('average_rating', models.DecimalField(decimal_places=1, default=Decimal('0'), editable=False, max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0, editable=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('price_at_order_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('IRT', 'IRT T'), ('USD', 'USD $')], default='IRR', editable=False, max_length=3)),
                ('price_at_order', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='IRR', help_text='Product price captured at order time.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dpi', models.PositiveIntegerField(blank=True, help_text='Max DPI.', null=True)),
                ('connection_type', models.IntegerField(choices=[(0, 'Wired'), (1, 'Wireless'), (2, 'Wired / Wireless')])),
                ('is_gaming', models.BooleanField(default=False)),
                ('has_rgb', models.BooleanField(default=False)),
                ('buttons_count', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_grams', models.PositiveIntegerField(blank=True, help_text='Weight in grams.', null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mouse_specs', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Mouse Spec',
            },
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_gaming', models.BooleanField(default=False)),
                ('layout', models.CharField(blank=True, choices=[('FULL', 'Full-size'), ('TKL', 'Tenkeyless'), ('60', '60%'), ('75', '75%'), ('65', '65%')], max_length=10)),
                ('switch_type', models.CharField(blank=True, choices=[('MECHANICAL', 'Mechanical'), ('MEMBRANE', 'Membrane'), ('OPTICAL', 'Optical'), ('HALL', 'Hall Effect')], max_length=20)),
                ('has_rgb', models.BooleanField(default=False)),
                ('has_num_pad', models.BooleanField(default=True)),
                ('is_wireless', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keyboard_specs', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Keyboard Spec',
            },
        ),
        migrations.CreateModel(
            name='HardDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('capacity_gb', models.PositiveIntegerField()),
                ('drive_type', models.IntegerField(choices=[(0, 'HDD'), (1, 'SSD'), (2, 'NVMe')])),
                ('form_factor', models.CharField(blank=True, help_text='e.g. 2.5", 3.5", M.2', max_length=20)),
                ('interface', models.CharField(blank=True, help_text='e.g. SATA III, PCIe 4.0 x4.', max_length=30)),
                ('read_speed_mb_s', models.PositiveIntegerField(blank=True, help_text='Sequential read MB/s.', null=True)),
                ('write_speed_mb_s', models.PositiveIntegerField(blank=True, help_text='Sequential write MB/s.', null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hard_specs', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Hard Drive Spec',
            },
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('memory_gb', models.PositiveIntegerField(help_text='VRAM in GB.')),
                ('memory_type', models.CharField(help_text='e.g. GDDR7, GDDR6X.', max_length=20)),
                ('core_clock_mhz', models.PositiveIntegerField(help_text='Base core clock in MHz.')),
                ('boost_clock_mhz', models.PositiveIntegerField(blank=True, help_text='Boost clock in MHz.', null=True)),
                ('tdp_watts', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gpu_specs', to='catalog.product')),
            ],
            options={
                'verbose_name': 'GPU Spec',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cores', models.PositiveIntegerField()),
                ('threads', models.PositiveIntegerField()),
                ('base_clock', models.DecimalField(decimal_places=2, help_text='Base clock in GHz.', max_digits=4)),
                ('boost_clock', models.DecimalField(decimal_places=2, help_text='Boost clock in GHz.', max_digits=4)),
                ('socket', models.CharField(help_text='e.g. AM5, LGA1851.', max_length=50)),
                ('tdp_watts', models.PositiveIntegerField(blank=True, help_text='Thermal design power in watts.', null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_specs', to='catalog.product')),
            ],
            options={
                'verbose_name': 'CPU Spec',
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Comment',
                'verbose_name_plural': 'Product Comments',
                'ordering': ['-created'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('capacity_gb', models.PositiveIntegerField(help_text='Capacity in GB.')),
                ('speed_mhz', models.PositiveIntegerField(help_text='Speed in MHz.')),
                ('ddr_type', models.PositiveSmallIntegerField(help_text='DDR generation (e.g. 4 for DDR4, 5 for DDR5).', validators=[django.core.validators.MinValueValidator(1)])),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ram_specs', to='catalog.product')),
            ],
            options={
                'verbose_name': 'RAM Spec',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='catalog_ord_status_ceaa79_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_id'], name='catalog_ord_order_i_8c54b6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='catalog_ord_user_id_cab66a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'stock'], name='catalog_pro_status_930a77_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='catalog_pro_slug_2b1eb6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
